### ISSUE TITLE
"Yearly" recurring option

### ISSUE THREAD

**Issue by codingthat** [xuhcc/mindstream#15]
I would find this very useful!  :)

Everyone would use mindstream for birthdays and maintenance tasks, right?  ;)

**Comment by codingthat** [comment]
Thanks so much for this—here's the other piece!  https://github.com/xuhcc/mindstream/pull/18

**Comment by codingthat** [comment]
BTW, works great :)

**Comment by xuhcc** [comment]
Thanks for your PR
I'll close this issue now.
