### ISSUE TITLE
If server stops running, UI silently begins losing all data, while appearing not to

### ISSUE THREAD

**Issue by codingthat** [xuhcc/mindstream#17]
Some kind of toaster/popup would be great while the front and back end are disconnected.  That or some localstorage use while changes are pending sync to the server, because even if the server is restarted, the data remains lost, as soon as the UI tab closes.

The /plaintext even makes it look as if everything is getting saved OK, when it's not—although, this is a great way to then save said data, if one knows they need to.

**Comment by xuhcc** [comment]
@codingthat The app should show alert now when reading/writing operation fails

**Comment by codingthat** [comment]
Thanks @xuhcc for the quick fix!
