### ISSUE TITLE
Allow more recurrence options

### ISSUE THREAD

**Issue by oli-ver** [xuhcc/mindstream#5]
Right now the regex for recurrences only allows to set 1-7 days, weeks or months:

```typescript
export const RECURRENCE_REGEXP = /^([1-7])(d|w|m)$/
const RECURRENCE_TAG_REGEXP = /rec:([1-7](d|w|m))(\s|$)/
```

In my opinion the recurrence should also be possible for other options every 13 days, every 19 weeks or every 104 months. There should be no need to only allow 1 to 7.

**Comment by xuhcc** [comment]
@oli-ver I agree with that. Thank you for your contribution!
