### ISSUE TITLE
Unable to find or change todo.txt

### ISSUE THREAD

**Issue by tonhou** [xuhcc/mindstream#9]
Android 10
Nokia 2.2

From Settings --> Browse cannot find todo.txt file
No error message, just nothing found.

Mindstream 1.5.0

**Comment by xuhcc** [comment]
Do you mean that nothing happens when you press the "Browse" button or that you can't pick the file using the file browser?

**Comment by tonhou** [comment]
Cannot pick the file. The file browser works but no todo.txt can be
found/seen.

**Comment by xuhcc** [comment]
There's a known bug in file picker where it fails to pick files from some locations on Android 10 (like 'Documents'). But in that case the app should show error message at the bottom of the screen: `Error: Can not get file path`.

**Comment by tonhou** [comment]
No error message.

By default pressing "Browse" goes to:

Android/data/im.mindstream.mobile/cache/http

The only file in that folder is:

"journal"

**Comment by xuhcc** [comment]
You can create an empty todotxt file somewhere and then open it with the app.

But if you want to find the file created by the app, that might not be possible in file browser (apparently the file browser can't show it because accessing application data folder requires root permissions).

**Comment by tonhou** [comment]
Yes, that works.

Is it possible for app to save outside of root so todo.txt is accessible?
Also is it possible that the "Plain text" page under the menu might be
selectable to copy?

Thanks for your direction.

The app I find most satisfactory.

**Comment by xuhcc** [comment]
>Is it possible for app to save outside of root so todo.txt is accessible?

Yes. I'll fix this in the next release.

>Also is it possible that the "Plain text" page under the menu might be
selectable to copy?

I'll have a look to see if that's possible.

**Comment by xuhcc** [comment]
@tonhou 1.6.0 has been released. The text at "plain text" page is selectable now.
